WRITE_THE_COUNT_OF_DAYS = "Напиши количество дней"
NUMBER_MILES = "Количество милей"
NUMBER_KM = "Количество километров"
NUMBER_AU = "Количество астрономических единиц"
DELAY_HOURS = "Задержка в часах"
